# Generated by Django 5.1.1 on 2024-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_blognews_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognews',
            name='title',
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок на англ'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок на каз'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок на рус'),
        ),
    ]
